version: '3.9'

services:
  server:
    container_name: budgettracker-api
    build:
      context: .
      dockerfile: BudgetTracker.Server/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=Server=db;Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD}
      
  client:
    container_name: budgettracker-client
    image: node:18
    working_dir: /app
    volumes:
      - ./budgettracker.client:/app
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install &&
             npm run build &&
             npx serve -s dist"

  db:
    container_name: budgettracker-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
